# Go to sleep after one hour (1*60*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y

# Hide layer changes that are momentary (using &mo, &lt etc.) from the layer widget (reduces the number of partial refreshes)
CONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y

# Add a periodic full display refresh (to clear up ghosting) (to refresh every N seconds)
CONFIG_ZMK_DISPLAY_FULL_REFRESH_PERIOD=5

# Invert displays to white-on-black instead of black-on-white
CONFIG_IL0323_INVERT=y

# Hide the "LAYER" heading in the layer widget and realign all widgets
CONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y

# Select different logo images to replace the "Corne-ish Zen" logo on the right half
# CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_ZMK=y
# CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_LPKB=y
# CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y

# Enable driver tweak to reduce ghosting for partial refreshes
CONFIG_IL0323_ALTERNATIVE_REFRESH=y